In [1]:
from pathlib import Path

print("Current working directory:", Path.cwd())
print("Dataset folder exists:", Path("data").exists())
print("Manifest exists:", Path("data/manifest.csv").exists())

Current working directory: c:\Users\fgmam\Documents\GitHub\Medical-Imaging-Research\Code\models\Model_2_GLCM+Wavelets_Random_Forest
Dataset folder exists: False
Manifest exists: False

In [2]:
from pathlib import Path

DATA_ROOT = Path("data")

if not DATA_ROOT.exists():
    print("The data folder does not exist.")
else:
    print("Contents of data folder:\n")

    for path in sorted(DATA_ROOT.iterdir()):
        print("[DIR]" if path.is_dir() else "[FILE]", path.name)

The data folder does not exist.

In [3]:
from pathlib import Path
from collections import Counter

DATA_ROOT = Path("data")

extensions = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}

images = [
    p for p in DATA_ROOT.rglob("*")
    if p.is_file() and p.suffix.lower() in extensions
]

print("Total image files:", len(images))

print("\nFirst 20 image paths:")
for path in images[:20]:
    print(path)

print("\nImage counts by parent folder:")
counts = Counter(p.parent.name for p in images)

for folder, count in counts.most_common(20):
    print(f"{folder}: {count}")

Total image files: 0

First 20 image paths:

Image counts by parent folder:

In [4]:
from pathlib import Path

DATA_ROOT = Path("data")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

print("Dataset directory:", DATA_ROOT.resolve())
print("Directory exists:", DATA_ROOT.exists())

Dataset directory: C:\Users\fgmam\Documents\GitHub\Medical-Imaging-Research\Code\models\Model_2_GLCM+Wavelets_Random_Forest\data
Directory exists: True

In [5]:
from pathlib import Path
from collections import Counter

DATA_ROOT = Path("data")

image_extensions = {
    ".png", ".jpg", ".jpeg",
    ".tif", ".tiff", ".bmp"
}

images = [
    p for p in DATA_ROOT.rglob("*")
    if p.is_file() and p.suffix.lower() in image_extensions
]

print("Dataset directory:", DATA_ROOT.resolve())
print("Total image files:", len(images))

print("\nTop-level contents:")
for path in sorted(DATA_ROOT.iterdir()):
    print("[DIR]" if path.is_dir() else "[FILE]", path.name)

print("\nFirst 15 image paths:")
for path in images[:15]:
    print(path)

print("\nImage counts by parent folder:")
counts = Counter(p.parent.name for p in images)

for folder, count in counts.most_common(20):
    print(f"{folder}: {count}")

print("\nMetadata files:")
for p in DATA_ROOT.rglob("*"):
    if p.is_file() and p.suffix.lower() in {".csv", ".json", ".xlsx"}:
        print(p)

Dataset directory: C:\Users\fgmam\Documents\GitHub\Medical-Imaging-Research\Code\models\Model_2_GLCM+Wavelets_Random_Forest\data
Total image files: 0

Top-level contents:

First 15 image paths:

Image counts by parent folder:

Metadata files:

In [7]:
from pathlib import Path
import json
import pandas as pd

PROJECT_DIR = Path.cwd()

DATA_ROOT = (
    PROJECT_DIR / ".." / ".." / ".."
    / "Datasets" / "Brain Tumor 12K Mri Images"
).resolve()

IMAGE_ROOT = DATA_ROOT / "Images_" / "Images_"
MANIFEST = PROJECT_DIR / "data" / "manifest.csv"

with open(DATA_ROOT / "DATA.json", "r", encoding="utf-8") as f:
    metadata = json.load(f)

print("Dataset found:", DATA_ROOT.exists())
print("Image directory found:", IMAGE_ROOT.exists())
print("Metadata records:", len(metadata))

Dataset found: True
Image directory found: True
Metadata records: 12643

In [8]:
records = []

for relative_path, info in metadata.items():

    # Original MRI image, not mask or bounding box
    image_file = IMAGE_ROOT / Path(relative_path)

    if not image_file.is_file():
        continue

    lesion = info.get("has_lesion")

    # Only use records with explicit binary labels
    if lesion not in (0, 1, False, True):
        continue

    label = "tumor" if lesion == 1 else "no_tumor"

    records.append({
        "image_path": str(image_file.resolve()),
        "label": label,
        "tumor_type": info.get("tumor_type"),
        "sequence": info.get("sequence"),
        "patient_id": info.get("patient_id")
    })

manifest_df = pd.DataFrame(records)

print("Total valid MRI images:", len(manifest_df))
print("\nClassification labels:")
print(manifest_df["label"].value_counts())

print("\nMissing patient IDs:")
print(manifest_df["patient_id"].isna().sum())

display(manifest_df.head())

Total valid MRI images: 11520

Classification labels:
label
tumor       10323
no_tumor     1197
Name: count, dtype: int64

Missing patient IDs:
11520

,image_path,label,tumor_type,sequence,patient_id
0,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,None
1,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,None
2,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,None
3,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,None
4,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,None

In [9]:
MANIFEST.parent.mkdir(parents=True, exist_ok=True)

manifest_df.to_csv(MANIFEST, index=False)

print("Manifest saved successfully!")
print("Location:", MANIFEST)
print("Total rows:", len(manifest_df))

Manifest saved successfully!
Location: c:\Users\fgmam\Documents\GitHub\Medical-Imaging-Research\Code\models\Model_2_GLCM+Wavelets_Random_Forest\data\manifest.csv
Total rows: 11520

In [10]:
check_df = pd.read_csv(MANIFEST)

print("Manifest rows:", len(check_df))
print("Columns:", check_df.columns.tolist())
print("\nLabels:")
print(check_df["label"].value_counts())

print("\nPatient identifiers available:")
print(check_df["patient_id"].notna().sum())

display(check_df.head())

Manifest rows: 11520
Columns: ['image_path', 'label', 'tumor_type', 'sequence', 'patient_id']

Labels:
label
tumor       10323
no_tumor     1197
Name: count, dtype: int64

Patient identifiers available:
0

,image_path,label,tumor_type,sequence,patient_id
0,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,NaN
1,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,NaN
2,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,NaN
3,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,NaN
4,C:\Users\fgmam\Documents\GitHub\Medical-Imagin...,tumor,Medulloblastoma,T1,NaN